// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayaorlmpktziwkdngvdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5YW9ybG1wa3R6aXdrZG5ndmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTkxOTgsImV4cCI6MjA2ODk3NTE5OH0.hPBCeqI6toHy_a_mnvL1TmvMvhJ3KG-6wZ3M9dbIO-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});